### ISSUE TITLE
Mongo is not defined

### ISSUE THREAD

**Issue by Monierv** [Urigo/meteor-rxjs#204]
Hi !
I'm having the error 'Mongo is not defined' 
````
import { MongoObservable } from 'meteor-rxjs';

const Boxes = new MongoObservable.Collection('boxes');
````
Someone got the same issue ?

**Comment by weini01** [comment]
Hi,
I also have a Problem with mongo since the last update (update from 0.4.7 to 0.4.13) 
I´m on Meteor 1.7.0.1 with mongo 1.5.0 and rxjs 6.1.0. and got the following Error:
`... /dev_bundle/server-lib/node_modules/fibers/future.js:280
throw(ex);
Error: Cannot find module 'meteor/mongo'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
 at require (internal/module.js:11:18)
at subscribeEvents (node_modules/meteor-rxjs/dist/bundles/index.umd.js:2:102)
at Object.<anonymous> (... /node_modules/meteor-rxjs/dist/bundles/index.umd.js:5:2)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at npmRequire (.../.meteor/local/build/programs/server/npm-require.js:133:10)
at Module.useNode (packages/modules-runtime.js:699:18)
at index.umd.js (packages/modules.js:272:8)
at fileEvaluate (packages/modules-runtime.js:339:7)
at require (packages/modules-runtime.js:238:16)
at images.collection.js (both/images/images.collection.ts:1:1)
at fileEvaluate (packages/modules-runtime.js:339:7)
at require (packages/modules-runtime.js:238:16)
at index.js (both/images/index.ts:3:1)
`

**Comment by vnavarroingenia** [comment]
Hi,

I have the same issue using  1.7.0.1

**Comment by mrz5018** [comment]
I'm having the same issue, without upgrading to 1.7.0.1.  I am thinking that it popped up when I updated angular to V6.x and rxjs to V6.x.  Not sure it it's either of those things, but I don't think it's specifically Meteor 1.7.

**Comment by ymchun** [comment]
I have this problem since version 0.4.12

**Comment by vnavarroingenia** [comment]
Hi @ardatan,
It works now for me using Meteor 1.7.0.1 and Angular 6.
Thanks!
